### ISSUE TITLE
无法安装

### ISSUE THREAD

**Issue by CloudlessMoon** [DevYao/JSONConverter#16]
<img width="420" alt="图片" src="https://user-images.githubusercontent.com/22904757/92886925-ab79dd80-f446-11ea-9dae-c5947cc88eb1.png">

**Comment by vvkeep** [comment]
#### 1.macOS 10.15之前使用需要打开允许任何和来源

终端中输入命令：
```
sudo spctl --master-disable
```
#### 2.macOS 10.15及之后的系统安全导致的些解决办法如下

终端中输入命令：
```
sudo xattr -r -d com.apple.quarantine+空格+app路经 

// 例如
sudo xattr -r -d com.apple.quarantine /Applications/JSONConverter.app 
```

#### 3.macOS 10.15及之后如果以上操作还不行可尝试以下方法
访达-应用程序-JSONConverter, 右键-显示简介-覆盖恶意软件保护 打勾 - 仍然允许 - 输入密码确认操作即可

#### 4.源码安装
可以下载源码，更改一下Bundle id, 编译代码生成App 使用，在Products目录中，找到APP 拖至 系统应用(Applications)目录下即可

**Comment by zhufaming** [comment]
还是不能解决问题，《访达-应用程序-JSONConverter, 右键-显示简介-覆盖恶意软件保护 打勾 - 仍然允许 - 输入密码确认操作即可》没有看到覆盖恶意软件保护选项，


`Process:               JSONConverter [10006]
Path:                  /Applications/JSONConverter.app/Contents/MacOS/JSONConverter
Identifier:            com.devyao.JSONConverter
Version:               ???
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           JSONConverter [10006]
User ID:               501

Date/Time:             2020-10-09 14:26:20.287 +0800
OS Version:            Mac OS X 10.15.6 (19G2021)
Report Version:        12
Anonymous UUID:        FFC9064D-C071-8C9C-C8A0-DF7E509F12EA


Time Awake Since Boot: 22000 seconds

System Integrity Protection: disabled

Crashed Thread:        0

Exception Type:        EXC_CRASH (Code Signature Invalid)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    Namespace CODESIGNING, Code 0x1

kernel messages:

VM Regions Near 0 (cr2):
--> 
    __TEXT                 0000000102bda000-0000000102c0a000 [  192K] r-x/r-x SM=COW  

Thread 0 Crashed:
0   @l$                          	0x000000010e813000 _dyld_start + 0

Thread 0 crashed with X86 Thread State (64-bit):
  rax: 0x0000000000000000  rbx: 0x0000000000000000  rcx: 0x0000000000000000  rdx: 0x0000000000000000
  rdi: 0x0000000000000000  rsi: 0x0000000000000000  rbp: 0x0000000000000000  rsp: 0x00007ffeed025c50
   r8: 0x0000000000000000   r9: 0x0000000000000000  r10: 0x0000000000000000  r11: 0x0000000000000000
  r12: 0x0000000000000000  r13: 0x0000000000000000  r14: 0x0000000000000000  r15: 0x0000000000000000
  rip: 0x000000010e813000  rfl: 0x0000000000000200  cr2: 0x0000000000000000
  
Logical CPU:     0
Error Code:      0x00000000
Trap Number:     0


Binary Images:
       0x102bda000 -        0x102c09fff +@l$ (0) <06281E33-9707-3F9A-9F92-AF0730D158DC> @l$
       0x10e812000 -        0x10e8a3f47 +@l$ (750.6) <F9D4DEDC-8296-3E3F-B517-9C8B89A4C094> @l$

External Modification Summary:
  Calls made by other processes targeting this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by all processes on this machine:
    task_for_pid: 63118
    thread_create: 0
    thread_set_state: 24

VM Region Summary:
ReadOnly portion of Libraries: Total=1348K resident=0K(0%) swapped_out_or_unallocated=1348K(100%)
Writable regions: Total=8408K written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=8408K(100%)
 
                                VIRTUAL   REGION 
REGION TYPE                        SIZE    COUNT (non-coalesced) 
===========                     =======  ======= 
STACK GUARD                       56.0M        1 
Stack                             8192K        1 
__DATA                             252K        4 
__DATA_CONST                        28K        2 
__LINKEDIT                         572K        2 
__TEXT                             776K        2 
shared memory                        8K        2 
===========                     =======  ======= 
TOTAL                             65.6M       14 

Model: Macmini7,1, BootROM 249.0.0.0.0, 2 processors, Dual-Core Intel Core i5, 2.6 GHz, 16 GB, SMC 2.24f32
Graphics: kHW_IntelIrisItem, Intel Iris, spdisplays_builtin
Memory Module: BANK 0/DIMM0, 8 GB, DDR3, 1600 MHz, 0x80AD, 0x483943434E4E4E434C47414C41522D4E5644
Memory Module: BANK 1/DIMM0, 8 GB, DDR3, 1600 MHz, 0x80AD, 0x483943434E4E4E434C47414C41522D4E5644
AirPort: spairport_wireless_card_type_airport_extreme (0x14E4, 0x13B), Broadcom BCM43xx 1.0 (7.77.111.1 AirPortDriverBrcmNIC-1615.1)
Bluetooth: Version 7.0.6f7, 3 services, 27 devices, 1 incoming serial ports
Network Service: Wi-Fi, AirPort, en1
Network Service: iPhone, Ethernet, en5
Serial ATA Device: APPLE SSD SM0256G, 251 GB
USB Device: USB 3.0 Bus
USB Device: IR Receiver
USB Device: BRCM20702 Hub
USB Device: Bluetooth USB Host Controller
USB Device: USB Receiver
USB Device: iPhone
Thunderbolt Bus: Mac mini, Apple Inc., 26.1
`

**Comment by vvkeep** [comment]
实在不行 先clone 代码 跑一下吧
